### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/spm#13]
* [x] Makefile
* [x] homebrew
* [x] for windows binary
* [ ] auto creation for package.toml
* [x] installation by curl
* [ ] interactive credential input
