### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/spm#8]
## Todo
* [x] use logger interface
* [x] add test code for sub directory
* [x] add README for sub directory
* [x] use fmt.Sprintf for concat strings
* [x] use const for error string, regex etc.
* [x] up version number
